import type { Metadata } from 'next';
// import { Inter } from "next/font/google";
import './tailwind.css';

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'BarelyHR',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://api.fontshare.com/css?f[]=switzer@400,500,600&display=swap"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
